version: '3.1'

services:
  mongo:
    image: mongo:4.2.3
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  mongo-seed:
    image: mongo:4.2.3
    command:
      - /bin/bash
      - -c
      - |
        mongoimport --host mongo:27017 --db test_db --collection users --drop
        mongoimport --host mongo:27017 --db test_db --collection users --type json --file /seed/users.json --jsonArray
        mongoimport --host mongo:27017 --db test_db --collection reviews --drop
        mongoimport --host mongo:27017 --db test_db --collection reviews --type json --file /seed/reviews.json --jsonArray
    volumes:
      - ./seed:/seed
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo

volumes:
  mongo:
